// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxoqwtutgojsgncxrsrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4b3F3dHV0Z29qc2duY3hyc3J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMzUzNjYsImV4cCI6MjA1ODcxMTM2Nn0.U_syxc3B8x9zuZp4a3RNiiS68hd5I7XAnXBoiVnZmKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);